---
title: "Coding Challenge. 4"
author: "Maryam Saeed Noor Fatima"
date: "2025-02-25"
output:
  md_document:
    variant: gfm
  word_document: default
  pdf_document: default
  html_document: 
   toc: true
   toc_float: true
---

# Coding Challenge 3

## **Q.No.3 (a)**

## **Q.No.6 (b)**

###Readme file link

[link to my Readme file](Coding challenge.4.md)

### Clickable Link to the ManuscDript

[Manuscript Link](i.	Noel, Z.A., Roze, L.V., Breunig, M., Trail, F. 2022. Endophytic fungi as promising biocontrol agent to protect wheat from Fusarium graminearum head blight. Plant Disease. https://doi.org/10.1094/PDIS-06-21-1253-RE)

## **Q.No.6 (b)**

##File Tree of Github 

[pdf file](Coding-challenge.4.pdf)

[word file](Coding-challenge.4.docx)

[md file](Coding-challenge.4.md)

[Mycotoxin csv file](MycotoxinData.csv)

### Libraries

```{r}
library(readr)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggrepel) 
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73",
                "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

## **Q.No.3 (b)**
### Importing the excel file
```{r}
MycotoxinData <- read.csv("MycotoxinData.csv",na = "na")
```


## **Q.No.3 (c)**
### Creating a ggplot box plot

```{r}
plot.1<- ggplot(data = MycotoxinData, aes(x = Treatment, y = DON, fill = Cultivar)) +
  geom_boxplot(color = "black") +  
  geom_point(aes(fill = Cultivar), shape = 21, color = "black", alpha = 0.6, 
             width = 0.9) + 
  scale_fill_manual(values = c(cbbPalette[6], cbbPalette[4])) +  
  xlab("") +
  ylab("DON(ppm)") + 
  theme_classic() + 
  facet_wrap(~Cultivar, scale = "free") 
plot.1

```

###  Changing the factor levels
```{r}
MycotoxinData$Treatment <- factor(MycotoxinData$Treatment,
                                  levels = c("NTC", "Fg", "Fg + 37", "Fg + 40", "Fg + 70"))
```



### a. Using 15ADON as Y variable

```{r}
plot.2 <- ggplot(data = MycotoxinData, aes(x = Treatment, y = X15ADON, fill = Cultivar)) +
  geom_boxplot(color = "black") +
  geom_point(aes(fill = Cultivar), shape = 21, color = "black", alpha = 0.6, 
             position = position_jitterdodge(dodge.width = 0.9)) +  
  scale_fill_manual(values = c(cbbPalette[6], cbbPalette[4])) +
  ylab("15ADON") +
  theme_classic() +
  facet_wrap(~Cultivar, scale = "free")
plot.2

```

 ### b. using MassperSeed_mg as Y variable
 

```{r}
plot.3<- ggplot(data = MycotoxinData, aes(x = Treatment, y = MassperSeed_mg , fill = Cultivar)) +
                                   geom_boxplot(color = "black") +  
                                   geom_point(aes(fill = Cultivar), shape = 21, color = "black", alpha = 0.6, 
                                              position = position_jitterdodge(dodge.width = 0.9)) +  
                                   scale_fill_manual(values = c(cbbPalette[6], cbbPalette[4])) +  
                                   xlab("") +
                                   ylab("MassperSeed_mg") + 
                                   theme_classic() + 
                                   facet_wrap(~Cultivar, scale = "free")
plot.3
```



### using ggarrange 

```{r}
plot.4<- ggarrange(plot.1, plot.2, plot.3,
                                                    nrow =3,
                                                    ncol= 1,
                                                    labels = "auto",
                                                    common.legend = T) 
                                 plot.4
```






